# Generated by Django 3.2 on 2022-03-12 00:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrait', cloudinary.models.CloudinaryField(max_length=255, verbose_name='potrait')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsapp.skills')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
