# Generated by Django 3.2 on 2022-03-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='skillsapp.Skills'),
        ),
    ]
